# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e9630e9228198aa27714f091173b090fbf42fd1bb831a2dd378ffecb226ec4bbf26c9ac1b1c68ff3d5c782fface8fa5b12c1f446e295dedf319590003098690

test:
  secret_key_base: d32c02fb931b293f7793f0a39db169e42109afa87c7af7cb7eead38cec60dc0928b4e13dc83e7d65ae4958999f071ec7425d3425848f33069e4ea0bde5920965

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
